apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zefzl3b2y-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zefzl3b2y-python 
  name: zefzl3b2y-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zefzl3b2y-python 
